Añado HUs y milestones en el readme principal para el objetivo 1
PacoCP5/proyecto-PCP pull request #2
Opened 2022-10-06 11:53 UTC by PacoCP5

2022-10-06 18:14 UTC, PacoCP5 commented
@JJ Solicito revisión

2022-10-09 15:37 UTC, mariavallejo20 commented
Hola @PacoCP5 he estado mirando tu objetivo 1 y voy a comentarte lo que pienso que podría mejorar:

* Creo que te faltarían los "Tipos de usuario", es decir, un apartado donde aparezcan los diferentes usuarios que necesitan una solución al problema que has planteado. 

* Por otro lado, las historias de usuario deben expresar siempre un beneficio para el cliente que esté relacionado con la lógica de negocio. Es decir, las historias de usuario que tienes creo que pertenecerían más al apartado de "Tipos de usuario" ya que estás contando el problema que tiene el usuario, pero no el beneficio.

Además, acuérdate de añadir la lista de comprobación del objetivo 1 al cuerpo del PR.

2022-10-13 06:58 UTC, mariavallejo20 commented
Hola de nuevo @PacoCP5, he revisado los cambios que has hecho y te comento un poco que pienso:
* Creo que en los "Tipos de usuario" podrías expresar un poco mejor cual es el problema de cada usuario y en las "Historias de usuario" cual es el beneficio, aun que quizás para el profesor esté ya correcto.
* Por otro lado, en los milestones también los desarrollaría un poco más, siempre teniendo en cuenta que cada milestone debe describir un PMV y que no debes incluir detalles de implementación.
Una vez le eches un vistazo a eso, creo que podrías pedirle revisión al profe. Desde mi punto de vista creo que lo tienes muy bien encaminado. 
Seguimos en contacto si necesitas cualquier cosa. Ánimo ya te queda poco :)

2022-10-13 10:58 UTC, PacoCP5 commented
@JJ Tras los últimos comentarios de mi compañera te pido revisión.

2022-10-13 11:08 UTC, mariavallejo20 requested changes

2022-10-13 11:08 UTC, mariavallejo20 commented on docs/Documentación-1/HUs.md
> +## [HU0] Julia necesita poder organizar mejor sus horarios para cuidar de su hijo
Se me había pasado decirte, que las HU no empiezan en el 0, deben empezar en el 1.

2022-10-13 11:08 UTC, mariavallejo20 commented on docs/Documentación-1/HUs.md
> +A Javier le ha tocado varias veces con un TCAE (Auxiliar de enfermería) con el cual la dinámica de trabajo no es buena y le gustaría poder elegir cambiar de compañero. Si pudiese elegir su expresar s
Revisa la última frase que creo que te has liado a la hora de expresarla.

2022-10-13 11:09 UTC, mariavallejo20 commented
Por último, creo que te falta añadir el milestone 2 a la lista de milestones de tu repositorio, ya que tienes añadidos el M0 y M1, pero no veo el M2.

2022-10-13 11:10 UTC, PacoCP5 commented on docs/Documentación-1/HUs.md
> +## [HU0] Julia necesita poder organizar mejor sus horarios para cuidar de su hijo
Sí, justo me he dado cuenta al ver los errores frecuentes en el material de esta semana. Gracias :smile:

2022-10-13 11:11 UTC, mariavallejo20 commented
Avísame cuando haya revisado esto. :kissing_smiling_eyes:

2022-10-13 11:16 UTC, PacoCP5 commented
@mariavallejo20 Creo que ya está todo, si ves algo más me dices :smiley_cat:

2022-10-13 11:22 UTC, mariavallejo20 approved these changes
En mi opinión ya está todo correcto. :blush:

2022-10-13 11:26 UTC, JJ approved these changes
👍 con las pequeñas objeciones que no afectan a la consecución del objetivo.

2022-10-13 11:26 UTC, JJ commented on README.md
> +Interfaz de usuario para la aplicación que permita a los usuarios introducir su preferencia de los horarios y muestre la asignación.
El interfaz de usuario no lo vamos a usar en esta asignatura. Necesitarías un interfaz de programación aquí.

2022-10-13 11:41 UTC, merged